In [4]:
import numpy as np


In [5]:
a = np.zeros(2, dtype="int")
print("Matrix a: \n", a)

b = np.zeros([2, 2], dtype="int")
print("Matrix b: \n", b)

c = np.zeros([3, 3], dtype="int")
print("Matrix c: \n", c)

Matrix a: 
 [0 0]
Matrix b: 
 [[0 0]
 [0 0]]
Matrix c: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
